In [ ]:
#array operations
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2 = np.array([[1, 2], [2, 3]])
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(" 1d array is:",array1)
print("2 d array is \n",array2)
print("3 d array is :\n",array3)
print("shape of array2 is :",array2.shape)
print("Shape of array3 is :",array3.shape)
print("Datatype of array1 is :",array1.dtype)
print("Mean of Array 1 is :",np.mean(array1))
print("Max of arraay 1 is :",np.max(array1))

 1d array is: [ 1  2  3  4  5  6  7  8  9 10]
2 d array is 
 [[1 2]
 [2 3]]
3 d array is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of array2 is : (2, 2)
Shape of array3 is : (3, 3)
Datatype of array1 is : int64
Mean of Array 1 is : 5.5
Max of arraay 1 is : 10


In [20]:
range_array = np.arange(1, 10, 2)
print(range_array)
linespace_arr = np.linspace(5,2,5)
print(linespace_arr)


[1 3 5 7 9]
[5.   4.25 3.5  2.75 2.  ]


In [21]:
zeros_arr = np.zeros((2, 3))
print("Zeros array:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((3, 2))
print("Ones array:\n", ones_arr)

# Array filled with a constant value
full_arr = np.full((2, 2), 7)
print("Full array:\n", full_arr)

# Identity matrix
identity_arr = np.eye(4)
print("Identity matrix:\n", identity_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# aran
# ge -> similar to Python range() but returns an array
range_arr = np.arange(0, 10, 2)   # start, stop, step
print("arange array:", range_arr)

# linspace -> evenly spaced numbers between start and stop (inclusive)
lin_arr = np.linspace(0, 1, 5)    # 5 numbers between 0 and 1
print("linspace array:", lin_arr)

# Random arrays
rand_arr = np.random.rand(2, 3)      # uniform distribution [0, 1)
randint_arr = np.random.randint(1, 100, size=(2, 3))  # random integers
print("Random float array:\n", rand_arr)
print("Random integer array:\n", randint_arr)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]
Random float array:
 [[0.6343572  0.39576537 0.73571824]
 [0.24904806 0.02806284 0.22540402]]
Random integer array:
 [[44 84 97]
 [61 97 81]]
